# 📄 Файл: config.yaml | Расположение: librarian_ai/config/config.yaml
# 📌 Назначение: конфигурация агента Librarian AI (название зафиксировано)
# 📥 Получает: настройки от разработчика или пользователя (LLM, пути, API)
# 📤 Передаёт: параметры в основной код и модули ядра
#  Файл config.yaml создан. Название агента зафиксировано как Librarian AI, переименование не предусмотрено, 
#чтобы обеспечить стабильность в связке с другими агентами и ядром фермы.
# Название агента — зафиксировано как Librarian AI, переименование не предусмотрено
name: librarian_ai
version: 0.3
role: document_librarian

# LLM-провайдер по умолчанию
llm_provider: yandex_gpt

# Пути к ресурсам
paths:
  database: db/librarian.db
  vector_store: knowledge/vector_store/
  logs: logs/log.txt

# Включение дополнительных агентов
integrations:
  osint_plus: true
  factory: true

# Язык по умолчанию
language: ru
